name = str(input("What is your name?: "))
city = str(input(f"{name}, what is your hometown?: "))
book = str(input(f"{name}, what is your favorite book?: "))
film = str(input(f"{name}, what is your favorite film?: "))
print(f"Hello, my name is {name}, my homecity is {city}, my favorite book is '{book}' and i like '{film}' film")
